# Generated by Django 4.1 on 2022-09-08 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lolpros", "0002_alter_player_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lolpros.player",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lolpros.team",
            ),
        ),
    ]
