# Generated by Django 4.1 on 2022-09-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lolpros", "0002_team_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="test",
        ),
    ]
