# Generated by Django 4.1 on 2022-09-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lolpros", "0003_alter_account_player_alter_player_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="LPHistory",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="nameHistory",
            field=models.TextField(blank=True, null=True),
        ),
    ]
