# Generated by Django 4.1 on 2022-11-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lolpros", "0004_alter_player_discordid"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="avgLosses",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="avgWins",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
