# Generated by Django 4.1 on 2022-09-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lolpros", "0004_account_lphistory_account_namehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
