# Generated by Django 4.1 on 2022-09-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lolpros", "0006_account_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="role",
        ),
        migrations.AddField(
            model_name="player",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
