# Generated by Django 4.1 on 2022-09-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lolpros", "0007_remove_account_role_player_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="lpUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lp", models.IntegerField(blank=True, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lolpros.account",
                    ),
                ),
            ],
        ),
    ]
