# Generated by Django 4.1 on 2022-09-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lolpros", "0008_lpupdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="LPHistory",
        ),
        migrations.RemoveField(
            model_name="account",
            name="nameHistory",
        ),
    ]
